package com.monyrama.ui.components;

import javax.swing.BorderFactory;
import javax.swing.JPanel;

public class MyProgressDialog extends javax.swing.JDialog {

    private javax.swing.JLabel myLabel;

	/** Creates new form MyProgressDialog */
    public MyProgressDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setResizable(false);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        myLabel = new javax.swing.JLabel();
        javax.swing.JProgressBar progressBar = new javax.swing.JProgressBar();

        JPanel panel = new JPanel();
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setContentPane(panel);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(myLabel, gridBagConstraints);

        progressBar.setIndeterminate(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        getContentPane().add(progressBar, gridBagConstraints);
    }// </editor-fold>

    public void setLabelText(String text) {
        myLabel.setText(text);
    }
    
    public void showMe() {
    	pack();
    	setVisible(true);
    }
    
    public void hideMe() {
    	dispose();
    }
}
