package com.monyrama.preferences;

public enum PrefKeys {
	MAIN_WINDOW_NAVIGATION_TREE_COLLAPSED, SHOW_WELCOME_SCREEN, NAVIGATION_ITEM,
	/*PASSWORD, obsolete key, was used to save open password*/
	PASSWORD_HASH,
	ACTIVE_EXPENSES_CHART_INDEX,
	CLOSED_EXPENSES_CHART_INDEX,
	ACTIVE_INCOMES_CHART_INDEX,
	CLOSED_INCOMES_CHART_INDEX,
	
	SERVER_PORT,
	SERVER_AUTO_START,
	
	LANGUAGE_CODE,
	
	DATAFOLDER_PATH,
	
	THEME,

	LAST_EXPENSE_ACCOUNT_ID,
	LAST_EXPENSE_ENVELOPE_ID
}
